version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: archiflow-db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: archiflow-api:latest
    container_name: archiflow-api
    restart: always
    build:
      context: .
      dockerfile: src/ArchiFlow.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXPIRATION_MINUTES=${JWT_EXPIRATION_MINUTES}
      - SEED_ADMIN_NAME=${SEED_ADMIN_NAME:-Administrador do Sistema}
      - SEED_ADMIN_EMAIL=${SEED_ADMIN_EMAIL:-admin@archiflow.com}
      - SEED_ADMIN_PASSWORD=${SEED_ADMIN_PASSWORD:-Admin@123}
      - SEED_GERENTE_NAME=${SEED_GERENTE_NAME:-Gerente Arquiteto}
      - SEED_GERENTE_EMAIL=${SEED_GERENTE_EMAIL:-gerente@archiflow.com}
      - SEED_GERENTE_PASSWORD=${SEED_GERENTE_PASSWORD:-Gerente@123}
      - SEED_COLABORADOR_NAME=${SEED_COLABORADOR_NAME:-Colaborador Arquiteto}
      - SEED_COLABORADOR_EMAIL=${SEED_COLABORADOR_EMAIL:-colaborador@archiflow.com}
      - SEED_COLABORADOR_PASSWORD=${SEED_COLABORADOR_PASSWORD:-Colaborador@123}
    ports:
      - "5000:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata:
