// <auto-generated />
using System;
using ArchiFlow.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArchiFlow.Infrastructure.Migrations
{
    [DbContext(typeof(ArchiFlowDbContext))]
    [Migration("20260809032434_AddLeadsTable")]
    partial class AddLeadsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArchiFlow.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CLI_Id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("CLI_Ativo");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CLI_Cpf_Cnpj");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CLI_Email");

                    b.Property<string>("Endereco")
                        .HasColumnType("text")
                        .HasColumnName("CLI_Endereco");

                    b.Property<Guid?>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("CLI_Lead_Id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("CLI_Nome");

                    b.Property<string>("SenhaPortal")
                        .HasColumnType("text")
                        .HasColumnName("CLI_Senha_Portal");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("CLI_Telefone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("ArchiFlow.Domain.Leads.HistoricoContatoLead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("HCL_Id");

                    b.Property<string>("Canal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("HCL_Canal");

                    b.Property<DateTime>("DataContato")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("HCL_Data_Contato");

                    b.Property<Guid>("LeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("HCL_Lead_Id");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("HCL_Resumo");

                    b.HasKey("Id");

                    b.HasIndex("LeadId");

                    b.ToTable("Historicos_Contato_Lead", (string)null);
                });

            modelBuilder.Entity("ArchiFlow.Domain.Leads.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("LED_Id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LED_Atualizado_Em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("LED_Criado_Em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("LED_Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("LED_Nome");

                    b.Property<string>("Origem")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("LED_Origem");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("LED_Status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("LED_Telefone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Leads", (string)null);
                });

            modelBuilder.Entity("ArchiFlow.Domain.Projetos.EtapaProjeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ETo_Id");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dETo_Data_Conclusao");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("ETo_Descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ETo_Nome");

                    b.Property<int?>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ETo_Ordem");

                    b.Property<Guid?>("ProjetoId")
                        .HasColumnType("uuid")
                        .HasColumnName("ETo_Projeto_Id");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("ETo_Status");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Etapas_Projeto", (string)null);
                });

            modelBuilder.Entity("ArchiFlow.Domain.Projetos.Projeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("PJT_Id");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PJT_Atualizado_Em");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("PJT_Cliente_Id");

                    b.Property<DateTime?>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PJT_Criado_Em");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PJT_Data_Inicio");

                    b.Property<DateTime?>("DataPrevistaEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("PJT_Data_Prevista_Entrega");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("PJT_Descricao");

                    b.Property<decimal?>("MetragemTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("PJT_Metragem_Total");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("PJT_Nome");

                    b.Property<int?>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("PJT_Status");

                    b.Property<int?>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("PJT_Tipo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Projetos", (string)null);
                });

            modelBuilder.Entity("ArchiFlow.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("USR_Id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("USR_Ativo");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USR_Atualizado_Em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("USR_Criado_Em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("USR_Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("USR_Nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("USR_Role");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("USR_Senha_Hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("ArchiFlow.Domain.Leads.HistoricoContatoLead", b =>
                {
                    b.HasOne("ArchiFlow.Domain.Leads.Lead", "Lead")
                        .WithMany("HistoricoContatos")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("ArchiFlow.Domain.Projetos.EtapaProjeto", b =>
                {
                    b.HasOne("ArchiFlow.Domain.Projetos.Projeto", "Projeto")
                        .WithMany("Etapas")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Projeto");
                });

            modelBuilder.Entity("ArchiFlow.Domain.Projetos.Projeto", b =>
                {
                    b.HasOne("ArchiFlow.Domain.Clientes.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("ArchiFlow.Domain.Leads.Lead", b =>
                {
                    b.Navigation("HistoricoContatos");
                });

            modelBuilder.Entity("ArchiFlow.Domain.Projetos.Projeto", b =>
                {
                    b.Navigation("Etapas");
                });
#pragma warning restore 612, 618
        }
    }
}
